//------------------------------------------------------------------------------
// <auto-generated>
//     Este código lo generó una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Distribuidora_Iumafis.Pages.Pagos
{


    public partial class EditarPago
    {
        protected global::System.Web.UI.WebControls.Panel pnlAlerta;
        protected global::System.Web.UI.WebControls.Label lblAlerta;
        protected global::System.Web.UI.WebControls.Label lblTitulo;
        protected global::System.Web.UI.WebControls.Label lblSubtitulo;
        protected global::System.Web.UI.WebControls.Panel pnlBtnImprimir;
        protected global::System.Web.UI.WebControls.Panel pnlAcciones;
        protected global::System.Web.UI.WebControls.DropDownList ddlPedido;
        protected global::System.Web.UI.WebControls.TextBox txtCliente;
        protected global::System.Web.UI.WebControls.DropDownList ddlTipoPago;
        protected global::System.Web.UI.WebControls.TextBox txtMonto;
        protected global::System.Web.UI.WebControls.TextBox txtCuotas;
        protected global::System.Web.UI.WebControls.TextBox txtFecha;
        protected global::System.Web.UI.WebControls.Button btnGuardar;
    }
}
