//------------------------------------------------------------------------------
// <auto-generated>
//     Este código lo generó una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Distribuidora_Iumafis.Pages.Pedidos
{


    public partial class CrearPedido
    {
        protected global::System.Web.UI.WebControls.Panel pnlAlerta;
        protected global::System.Web.UI.WebControls.Label lblAlerta;
        protected global::System.Web.UI.WebControls.DropDownList ddlCliente;
        protected global::System.Web.UI.WebControls.Button btnAgregarFila;
        protected global::System.Web.UI.WebControls.Repeater rptDetalle;
        protected global::System.Web.UI.WebControls.Label lblTotal;
        protected global::System.Web.UI.WebControls.Button btnGuardar;
    }
}
