//------------------------------------------------------------------------------
// <auto-generated>
//     Este código lo generó una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Distribuidora_Iumafis.Pages.Pedidos
{


    public partial class DetallePedido
    {
        protected global::System.Web.UI.WebControls.Panel pnlAlerta;
        protected global::System.Web.UI.WebControls.Label lblAlerta;
        protected global::System.Web.UI.WebControls.Label lblPedidoId;
        protected global::System.Web.UI.WebControls.Label lblFecha;
        protected global::System.Web.UI.WebControls.Label lblCliente;
        protected global::System.Web.UI.WebControls.Label lblEstado;
        protected global::System.Web.UI.WebControls.Label lblTotal;
        protected global::System.Web.UI.WebControls.Repeater rptDetalles;
        protected global::System.Web.UI.WebControls.GridView gvPagos;
        protected global::System.Web.UI.WebControls.Label lblPagosVacio;
    }
}
