//------------------------------------------------------------------------------
// <auto-generated>
//     Este código lo generó una herramienta.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Distribuidora_Iumafis.Pages.Reportes
{
    public partial class Reportes
    {
        protected global::System.Web.UI.WebControls.TextBox txtDesde;
        protected global::System.Web.UI.WebControls.TextBox txtHasta;
        protected global::System.Web.UI.WebControls.Button btnGenerar;
        protected global::System.Web.UI.WebControls.Button btnLimpiar;
        protected global::System.Web.UI.WebControls.Panel pnlResumen;
        protected global::System.Web.UI.WebControls.Label lblTotalVentas;
        protected global::System.Web.UI.WebControls.Label lblTotalPedidos;
        protected global::System.Web.UI.WebControls.Label lblTotalProductosVendidos;
        protected global::System.Web.UI.WebControls.Label lblTotalCancelados;
        protected global::System.Web.UI.WebControls.GridView gvProductos;
        protected global::System.Web.UI.WebControls.Label lblProductosVacio;
        protected global::System.Web.UI.WebControls.GridView gvClientes;
        protected global::System.Web.UI.WebControls.Label lblClientesVacio;
        protected global::System.Web.UI.WebControls.GridView gvFechas;
        protected global::System.Web.UI.WebControls.Label lblFechasVacio;
        protected global::System.Web.UI.WebControls.GridView gvCategorias;
        protected global::System.Web.UI.WebControls.Label lblCategoriasVacio;
        protected global::System.Web.UI.WebControls.GridView gvEstados;
    }
}
