//------------------------------------------------------------------------------
// <auto-generated>
//     Este código lo generó una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Distribuidora_Iumafis.Pages.Productos
{


    public partial class CrearProducto
    {
        protected global::System.Web.UI.WebControls.Panel pnlAlerta;
        protected global::System.Web.UI.WebControls.Label lblAlerta;
        protected global::System.Web.UI.WebControls.TextBox txtNombre;
        protected global::System.Web.UI.WebControls.TextBox txtCategoria;
        protected global::System.Web.UI.WebControls.TextBox txtMarca;
        protected global::System.Web.UI.WebControls.TextBox txtDescripcion;
        protected global::System.Web.UI.WebControls.TextBox txtIngredientes;
        protected global::System.Web.UI.WebControls.TextBox txtBeneficios;
        protected global::System.Web.UI.WebControls.TextBox txtRecomendaciones;
        protected global::System.Web.UI.WebControls.TextBox txtPrecio;
        protected global::System.Web.UI.WebControls.TextBox txtStock;
        protected global::System.Web.UI.WebControls.CheckBox chkDisponibilidad;
        protected global::System.Web.UI.WebControls.DropDownList ddlDisponibilidad;
        protected global::System.Web.UI.WebControls.Button btnGuardar;
    }
}
