//------------------------------------------------------------------------------
// <auto-generated>
//     Este código lo generó una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Distribuidora_Iumafis.Pages.Clientes
{


    public partial class CrearCliente
    {
        protected global::System.Web.UI.WebControls.Panel pnlAlerta;
        protected global::System.Web.UI.WebControls.Label lblAlerta;
        protected global::System.Web.UI.WebControls.TextBox txtNombre;
        protected global::System.Web.UI.WebControls.DropDownList ddlTipoCliente;
        protected global::System.Web.UI.WebControls.TextBox txtTelefono;
        protected global::System.Web.UI.WebControls.TextBox txtEmail;
        protected global::System.Web.UI.WebControls.TextBox txtDireccion;
        protected global::System.Web.UI.WebControls.Button btnGuardar;
    }
}
