//------------------------------------------------------------------------------
// <auto-generated>
//     Este código lo generó una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Distribuidora_Iumafis.Pages.Clientes
{
    public partial class EditarCliente
    {
        protected global::System.Web.UI.WebControls.Panel pnlAlerta;
        protected global::System.Web.UI.WebControls.Label lblAlerta;
        protected global::System.Web.UI.WebControls.Label lblTitulo;
        protected global::System.Web.UI.WebControls.Label lblSubtitulo;
        protected global::System.Web.UI.WebControls.Panel pnlFormEdit;
        protected global::System.Web.UI.WebControls.Panel pnlFormulario;
        protected global::System.Web.UI.WebControls.Panel pnlHistorial;
        protected global::System.Web.UI.WebControls.Label lblClienteNombre;
        protected global::System.Web.UI.WebControls.Label lblClienteTipo;
        protected global::System.Web.UI.WebControls.Label lblClienteTel;
        protected global::System.Web.UI.WebControls.TextBox txtNombre;
        protected global::System.Web.UI.WebControls.DropDownList ddlTipoCliente;
        protected global::System.Web.UI.WebControls.TextBox txtTelefono;
        protected global::System.Web.UI.WebControls.TextBox txtEmail;
        protected global::System.Web.UI.WebControls.TextBox txtDireccion;
        protected global::System.Web.UI.WebControls.Button btnGuardar;
        protected global::System.Web.UI.WebControls.GridView gvHistorial;
        protected global::System.Web.UI.WebControls.Label lblHistorialVacio;

        /// <summary>
        /// control form1.
        /// </summary>
        /// <remarks>
        /// Campo generado automáticamente.
        /// Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
    }
}
